### ISSUE TITLE
Currency might be negative

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#75] opened 2020-06-25 01:57 UTC
We got this stack tract. I guess Currency gets negative in updateRevisionOutputs.

```
goroutine 1818429 [running]:
runtime/debug.Stack(0x450157, 0x0, 0xc001e348b0)
  /usr/local/Cellar/go/1.14.4/libexec/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
  /usr/local/Cellar/go/1.14.4/libexec/src/runtime/debug/stack.go:16 +0x22
gitlab.com/NebulousLabs/Sia/build.Critical(0xc001e34968, 0x1, 0x1)
  /Users/junpei/pkg/mod/gitlab.com/!nebulous!labs/!sia@v1.4.8/build/critical.go:20 +0xd9
gitlab.com/NebulousLabs/Sia/types.Currency.Sub(0x100c800, 0xc001edbee8, 0x1, 0x1, 0xc001e6a900, 0xc00230be80, 0x1, 0x1, 0x8ae625be92af5a00, 0x0, ...)
  /Users/junpei/pkg/mod/gitlab.com/!nebulous!labs/!sia@v1.4.8/types/currency.go:190 +0x14e
lukechampine.com/us/renter/proto.updateRevisionOutputs(0xc001e356a8, 0xc013533600, 0xc00230be80, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
  /Users/junpei/pkg/mod/lukechampine.com/us@v0.16.1-0.20200622035559-d9bd75f51730/renter/proto/session.go:754 +0x1e6
lukechampine.com/us/renter/proto.(*Session).RenewAndClearContract(0xc001dc8c00, 0x13e8320, 0xc001ec7ad0, 0x13d4a20, 0xc001ec7ad0, 0xc0018cea00, 0xc002515000, 0x2, 0x7, 0x40e20, ...)
  /Users/junpei/pkg/mod/lukechampine.com/us@v0.16.1-0.20200622035559-d9bd75f51730/renter/proto/renew.go:331 +0x155c
lukechampine.com/us/renter/proto.RenewContract(0x13e8320, 0xc001ec7ad0, 0x13d4a20, 0xc001ec7ad0, 0x789823fdbaaea4ea, 0x7105fea3fcb7ef0e, 0x8cf1488de1bb7ae0, 0x5661fc6f389adc5c, 0xc0018cea00, 0x40, ...)
  /Users/junpei/pkg/mod/lukechampine.com/us@v0.16.1-0.20200622035559-d9bd75f51730/renter/proto/renew.go:31 +0x271
```

**Comment by jkawamoto** [comment] 2020-06-25 02:17
Maybe it relates to https://github.com/lukechampine/us/pull/64.

**Comment by lukechampine** [comment] 2020-06-25 20:59
Hmm. It looks like the host requires a payment of `BaseRPCPrice` to complete the RPC, but the renter doesn't have enough. This is probably a bug on both sides: if the contract doesn't have at least `BaseRPCPrice` funds left, it should just go to zero.

**Comment by lukechampine** [comment] 2020-06-25 21:43
Panic fixed in https://github.com/lukechampine/us/pull/76, but renews will still be rejected until https://gitlab.com/NebulousLabs/Sia/-/merge_requests/4630 is merged.

**Comment by MeijeSibbel** [comment] 2020-06-27 00:52
![image](https://user-images.githubusercontent.com/11735738/85910800-3f151800-b821-11ea-8402-077b070632af.png)
Found it in our logs again. Is this still a panic?

**Comment by MeijeSibbel** [comment] 2020-06-27 00:59
`Critical error: (Sia v1.4.8, Release: standard) negative currency not allowed` --> Maybe related to https://gitlab.com/NebulousLabs/Sia/-/issues/4128 ?

**Comment by jkawamoto** [comment] 2020-06-27 04:11
@MeijeSibbel That server looks like it still uses the old version: `us@v0.16.1-0.20200622035559-d9bd75f51730`.

**Comment by lukechampine** [comment] 2020-07-09 16:43
If this is confirmed to be fixed, let's close this.

**Comment by MeijeSibbel** [comment] 2020-07-09 16:46
I haven't found this in the logs anymore so i think we can close it. Will comment if it resurfaces.

**Closed** 2020-07-09 17:01 UTC
